ログイン・ログアウト機能
shinonome-inc/backend-final-assignment-kobashi pull request #2
Opened 2024-03-15 03:11 UTC by KobashiYu

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-03-22 01:52 UTC, kotasuzuki72 approved these changes
LGTM

2024-03-22 01:52 UTC, kotasuzuki72 commented on accounts/views.py
> +    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
遷移先の画面を`settings.LOGIN_REDIRECT_URL`から取ってきている点が良いと思います．

2024-03-24 09:36 UTC, gaato requested changes

2024-03-24 09:36 UTC, gaato commented on accounts/tests.py
> +        )
`TestSignupView` と同様にリダイレクト先のステータスコードも確認しましょう！

2024-03-24 09:36 UTC, gaato commented on accounts/tests.py
> +        self.assertRedirects(response, reverse(LOGOUT_REDIRECT_URL), status_code=302)
ここも同様

2024-03-25 02:31 UTC, gaato approved these changes

2024-03-25 02:32 UTC, merged