ツイート機能
shinonome-inc/backend-final-assignment-kobashi pull request #3
Opened 2024-06-15 12:01 UTC by KobashiYu

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-06-26 22:43 UTC, Ash1ey18 requested changes, later dismissed
ツイート機能の実装お疲れ様でした！✨
大変良く書けていたと思います！！！
ささっと修正して、２次レビューに行っちゃってください！！😆

2024-06-26 22:43 UTC, Ash1ey18 commented on accounts/views.py
> +    def get(self, request, username):
renderメソッドを使用した実装ですね！👍
実は、今回はcontextを加えるだけなので、get_context_dataをオーバーライドして実装する方法もあります！
```
    def get_context_data(self, username):
        context = super().get_context_data()
        user = get_object_or_404(User, username=username)
        context["user"] = username
        context["tweets"] = Tweet.objects.select_related("user").filter(user=user).order_by("-created_at")
        return context
```
こんな感じです！！👍
僕の感覚ではcontextをいじるときはget_context_dataをいじることが多いかなって思うので、こっちの方法でも実装してみましょう！！🔥
↓参考サイト
 https://ccbv.co.uk/projects/Django/5.0/django.views.generic.base/TemplateView/
https://office54.net/python/django/views-render-how-to

2024-06-26 22:43 UTC, Ash1ey18 commented on accounts/views.py
> +        user = User.objects.get(username=username)
こちら、get_object_or_404を用いて記述することを薦めます！
理由、書き方はググって確認してみてください！🔥

2024-06-26 22:43 UTC, Ash1ey18 commented on tweets/tests.py
> +        self.assertEqual(response.context["tweet"], self.tweet)
こちら、self.tweetを用いてしまうとDBに保存されているか分からないので、（self.tweetはDBを参照しているわけではないから）`Tweet.objects`を用いて記述しましょう！👍
        `self.assertEqual(Tweet.objects.get(content=self.tweet.content),response.context["tweet"])
`

2024-06-28 10:16 UTC, Ash1ey18 commented
LGTM！お疲れ様です！！

2024-06-29 08:46 UTC, kotasuzuki72 approved these changes

2024-06-29 08:46 UTC, kotasuzuki72 commented on tweets/models.py
> +    def __str__(self):
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
分かりやすくて良いですね

2024-06-29 08:46 UTC, kotasuzuki72 commented on tweets/models.py
> +    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
Userモデルを持ってくる方法として，以下のようにget_user_modelを使う方法もあるので，覚えておくと良いと思います．
`from django.contrib.auth import get_user_model`
`from django.db import models`
`User = get_user_model()`
このようにして得た変数Userを，"accounts.User"に入れるということです．
修正はしなくて良いです．

2024-06-29 08:46 UTC, kotasuzuki72 commented
LGTM

2024-06-29 08:48 UTC, merged